name: Build and Release APK
on: push
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter command
        - uses: subosito/flutter-action@v1
          with:
            channel: 'dev'

        # Build Website
        - name: Build Website
          run: |
            flutter pub get
            flutter build web --web-renderer html --release
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting
          uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            args: deploy --only hosting:pet-rabbit-puzzle
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./
